export type FontSize =
  | 'xsmall'
  | 'small'
  | 'medium'
  | 'large'
  | 'xlarge'
  | 'xxlarge'
  | 'xxxlarge'
  | 'extra'
  | 'max'
  | 'xmax'
  | 'xxmax'
  | 'xxxmax'

export type Color =
  | 'silver'
  | 'white100'
  | 'white200'
  | 'white300'
  | 'black'
  | 'orange'
  | 'cyan'
  | 'green'
  | 'gray50'
  | 'gray100'
  | 'gray200'
  | 'gray300'
  | 'brown'
  | 'yellow100'
  | 'yellow200'
  | 'yellow300'
  | 'red100'
  | 'red200'
  | 'red300'
  | 'blue100'
  | 'blue200'
  | 'blue300'
  | 'green100'
  | 'lightRed'
  | 'primaryRed'
  | 'purple'
  | 'darkBlue'

export type Font = 'ubuntu' | 'roboto' | 'robotoCondensed'

export type Justify = 'flex-start' | 'center' | 'flex-end'

export type Align = 'flex-start' | 'center' | 'flex-end'

export type JustifyContent =
  | 'space-around'
  | 'center'
  | 'space-between'
  | 'flex-end'
  | 'flex-start'

export type TextAlign = 'left' | 'center' | 'right'

export type Spacing =
  | 'xxsmall'
  | 'xsmall'
  | 'small'
  | 'medium'
  | 'large'
  | 'xlarge'
  | 'xxlarge'
  | 'xxxlarge'

export type FontWeight = 'light' | 'normal' | 'semiBold' | 'bold'
